# Generated by Django 5.0.3 on 2024-05-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("store_app", "0006_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="payment",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.payment",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
